# Generated by Django 5.2.8 on 2025-11-09 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("f1_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discord_id",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("posted_at", models.DateTimeField(db_index=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("driver", models.CharField(blank=True, max_length=100, null=True)),
                ("author_id", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "author_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "author_nickname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("raw_content", models.TextField()),
                ("message_text", models.TextField(blank=True)),
                ("is_highlight_candidate", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="f1_data.session",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "posted_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "posted_at"],
                        name="f1_data_mes_session_22dc99_idx",
                    )
                ],
            },
        ),
    ]
